import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import About from './components/About'
import Banner from './components/Banner'
import Contact from './components/Contact'
import Experience from './components/Experience'
import Navigation from './components/navigation/Navigation'
import Skills from './components/Skills'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Jon Prell Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <Banner />
        <About />
        <Experience />
        <Skills />
        <Contact />
      </main>
      <footer>
        {'Made with <3 by Me'}
      </footer>
    </div>
  )
}

export default Home
